import { JsProduct } from './Product';

export const productData: Array<JsProduct> = [
    {
        id: 'E01',
        department: 'electronics',
        manufacturer: 'Apple',
        name: 'MacBook Pro',
        price: 699,
        isFeatured: true,
    },
    {
        id: 'E02',
        department: 'electronics',
        manufacturer: 'Apple',
        name: 'iMac',
        price: 1299,
        isFeatured: false,
    },
    {
        id: 'E03',
        department: 'electronics',
        manufacturer: 'Apple',
        name: 'iPad',
        price: 249,
        isFeatured: true,
    },
    {
        id: 'E04',
        department: 'electronics',
        manufacturer: 'Belkin',
        name: 'Belkin NetCam HD+ Wi-Fi Camera',
        price: 99,
        isFeatured: false,
    },
    {
        id: 'E05',
        department: 'electronics',
        manufacturer: 'Fitbit',
        name: 'Fitbit Charge HR',
        price: 136,
        isFeatured: true,
    },
    {
        id: 'E06',
        department: 'electronics',
        manufacturer: 'Ring',
        name: 'Ring Doorbell',
        price: 249,
        isFeatured: false,
    },
    {
        id: 'E07',
        department: 'electronics',
        manufacturer: 'August',
        name: 'August Smart Lock',
        price: 249,
        isFeatured: false,
    },
    {
        id: 'E08',
        department: 'electronics',
        manufacturer: 'Nest',
        name: 'Nest Thermostat',
        price: 249,
        isFeatured: true,
    },
    {
        id: 'E09',
        department: 'electronics',
        manufacturer: 'Nest',
        name: 'Nest Protect Smoke + Carbon Monoxide Alarm',
        price: 249,
        isFeatured: false,
    },
    {
        id: 'E10',
        department: 'electronics',
        manufacturer: 'Google',
        name: 'Google Chromecast',
        price: 35,
        isFeatured: false,
    },
    {
        id: 'E11',
        department: 'electronics',
        manufacturer: 'Nest',
        name: 'Nest Alarm ',
        price: 499,
        isFeatured: false,
    },
    {
        id: 'E12',
        department: 'electronics',
        manufacturer: 'Sonos',
        name: 'Sonos PLAY',
        price: 149,
        isFeatured: false,
    },
    {
        id: 'E13',
        department: 'electronics',
        manufacturer: 'Dyson',
        name: 'Dyson Vacuum',
        price: 175,
        isFeatured: false,
    },
    {
        id: 'E14',
        department: 'electronics',
        manufacturer: 'GoPro',
        name: 'GoPro HERO Session Action Camera',
        price: 149,
        isFeatured: false,
    },
    {
        id: 'E15',
        department: 'electronics',
        manufacturer: 'Google',
        name: 'Google Home Mini',
        price: 29,
        isFeatured: false,
    },
    {
        id: 'E16',
        department: 'electronics',
        manufacturer: 'Canon',
        name: 'Canon Rebel',
        price: 403,
        isFeatured: false,
    },
    {
        id: 'M01',
        department: 'music',
        manufacturer: 'Prince',
        name: 'Purple Rain',
        price: 22,
        isFeatured: true,
    },
    {
        id: 'M02',
        department: 'music',
        manufacturer: 'Norah Jones',
        name: 'Come Away With Me',
        price: 16,
        isFeatured: false,
    },
    {
        id: 'M03',
        department: 'music',
        manufacturer: 'Queen',
        name: 'A Night at the Opera',
        price: 12,
        isFeatured: true,
    },
    {
        id: 'M04',
        department: 'music',
        manufacturer: 'Charlie Puth',
        name: 'Nine Track Mind',
        price: 15,
        isFeatured: false,
    },
    {
        id: 'M05',
        department: 'music',
        manufacturer: 'Florence',
        name: 'Lungs',
        price: 15,
        isFeatured: false,
    },
    {
        id: 'M06',
        department: 'music',
        manufacturer: 'Meghan Trainor',
        name: 'Thank You',
        price: 8,
        isFeatured: true,
    },
    {
        id: 'M07',
        department: 'music',
        manufacturer: 'Amy Winehouse',
        name: 'Black to Black',
        price: 13,
        isFeatured: false,
    },
    {
        id: 'M08',
        department: 'music',
        manufacturer: 'Pharrell Williams',
        name: 'Happy',
        price: 12,
        isFeatured: false,
    },
    {
        id: 'M09',
        department: 'music',
        manufacturer: 'Michael Buble',
        name: 'Christmas',
        price: 9,
        isFeatured: false,
    },
    {
        id: 'M10',
        department: 'music',
        manufacturer: 'Michael Jackson',
        name: 'Thriller',
        price: 20,
        isFeatured: false,
    },
    {
        id: 'M11',
        department: 'music',
        manufacturer: 'Adele',
        name: '21',
        price: 19,
        isFeatured: false,
    },
    {
        id: 'M12',
        department: 'music',
        manufacturer: 'Bruno Mars',
        name: '24K Magic',
        price: 11,
        isFeatured: true,
    },
    {
        id: 'M13',
        department: 'music',
        manufacturer: 'The Beatles',
        name: 'Abbey Road',
        price: 21,
        isFeatured: false,
    },
    {
        id: 'M14',
        department: 'music',
        manufacturer: 'Pink Floyd',
        name: 'Dark Side of the Moon',
        price: 13,
        isFeatured: false,
    },
    {
        id: 'M15',
        department: 'music',
        manufacturer: 'Ed Sheeren',
        name: 'Divide',
        price: 15,
        isFeatured: false,
    },
    {
        id: 'M16',
        department: 'music',
        manufacturer: 'John Williams',
        name: 'Star Wars: The Last Jedi',
        price: 12,
        isFeatured: false,
    },
];
