export type ElementType =
    | 'block-quote'
    | 'bulleted-list'
    | 'heading1'
    | 'heading2'
    | 'heading3'
    | 'heading4'
    | 'heading5'
    | 'heading6'
    | 'image'
    | 'link'
    | 'list-item'
    | 'numbered-list'
    | 'paragraph'
    | 'pre';
